src/KITAB.SQLite.CRUD.Web/Common/Extensions/PaginationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace KITAB.SQLite.CRUD.Web.Extensions
{
    public class PaginationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/KITAB.SQLite.CRUD.Web/Controllers/ProdutosController.cs
using KITAB.SQLite.CRUD.Application.Notificadores;
using KITAB.SQLite.CRUD.Application.Produtos;
using KITAB.SQLite.CRUD.Domain.Models;
using KITAB.SQLite.CRUD.Infra.Paginacoes;
using KITAB.SQLite.CRUD.Web.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using System;
using System.IO;
using System.Collections.Generic;

namespace KITAB.SQLite.CRUD.Web.Controllers
{
    public class ProdutosController : BaseController
    {
        private readonly IProdutoService _produtoService;
        private readonly IMapper _mapper;
        private readonly IConfiguration _config;

        public ProdutosController(IProdutoService produtoService,
                                  INotificadorService notificadorService,
                                  IMapper mapper,
                                  IConfiguration config) : base(notificadorService)
        {
            _produtoService = produtoService;
            _mapper = mapper;
            _config = config;
        }

        [Route("produtos/lista")]
        [HttpGet]
        public IActionResult Index(int page, string sortField, string currentSortField, string currentSortOrder, string currentFilter, string filter)
        {
            if (_config.GetValue<bool>("StartProjectSettings:CreateTables:Produtos")) 
            {
                _produtoService.CriarTabelaProduto();
            }

            if (filter != null)
            {
                page = 1;
            }
            else
            {
                filter = currentFilter;
            }

            if (string.IsNullOrEmpty(sortField))
            {
                currentSortField = "Id";
                currentSortOrder = "ASC";
            }
            else
            {
                if (sortField != "*")
                {
                    if (currentSortField == sortField)
                    {
                        currentSortOrder = (currentSortOrder == "ASC" ? "DESC" : "ASC");
                    }
                    else
                    {
                        currentSortField = sortField;
                        currentSortOrder = "ASC";
                    }
                }
            }

            PaginacaoLista<Produto> _listaProdutos = _produtoService.ObterTodosPaginado(filter, (currentSortField + " " + currentSortOrder), page, 5);

            ViewBag.Paginacao = new PaginacaoDados {
                CurrentPage = _listaProdutos.PaginacaoDados.CurrentPage,
                HasNext = _listaProdutos.PaginacaoDados.HasNext,
                HasPrevious = _listaProdutos.PaginacaoDados.HasPrevious,
                PageSize = _listaProdutos.PaginacaoDados.PageSize,
                TotalCount = _listaProdutos.PaginacaoDados.TotalCount,
                TotalPages = _listaProdutos.PaginacaoDados.TotalPages,
                Filter = filter,
                SortField = currentSortField,
                SortOrder = currentSortOrder
            };

            return View(_mapper.Map<IEnumerable<ProdutoViewModel>>(_listaProdutos));
        }
        
        [Route("produtos/novo")]
        [HttpGet]
        public IActionResult Inserir()
        {
            return View();
        }

        [Route("produtos/novo")]
        [HttpPost]
        public IActionResult Inserir(ProdutoViewModel produtoViewModel)
        {
            // Faz a validação dos dados da camada de apresentação
            if (!ModelState.IsValid) return View(produtoViewModel);

            if (produtoViewModel.ImagemUpload != null)
            {
                var _imgPrefixo = (Guid.NewGuid() + "_");

                if (!UploadArquivo(produtoViewModel.ImagemUpload, _imgPrefixo)) return View(produtoViewModel);

                produtoViewModel.Imagem = (_imgPrefixo + produtoViewModel.ImagemUpload.FileName);
            }

            _produtoService.Inserir(_mapper.Map<Produto>(produtoViewModel));

            // Verifica se há notificações vinda da camada de negócio
            // Caso tenha notificações, devem ser exibidas ao usuário
            if (!OperacaoValida()) return View(produtoViewModel);

            return RedirectToAction("Index");
        }

        [Route("produtos/alterar/{id:int}")]
        [HttpGet]
        public IActionResult Alterar(int id)
        {
            ProdutoViewModel _produtoViewModel = _mapper.Map<ProdutoViewModel>(_produtoService.ObterPorId(id));

            if (_produtoViewModel == null) return NotFound();

            return View(_produtoViewModel);
        }

        [Route("produtos/alterar/{id:int}")]
        [HttpPost]
        public IActionResult Alterar(int id, ProdutoViewModel produtoViewModel)
        {
            if (id != produtoViewModel.Id) return NotFound();

            // Faz a validação dos dados da camada de apresentação
            if (!ModelState.IsValid) return View(produtoViewModel);

            if (produtoViewModel.ImagemUpload != null)
            {
                string _imgPrefixo = (Guid.NewGuid() + "_");

                if (!UploadArquivo(produtoViewModel.ImagemUpload, _imgPrefixo)) return View(produtoViewModel);

                produtoViewModel.Imagem = (_imgPrefixo + produtoViewModel.ImagemUpload.FileName);
            }

            _produtoService.Alterar(_mapper.Map<Produto>(produtoViewModel));

            // Verifica se há notificações vinda da camada de negócio
            // Caso tenha notificações, devem ser exibidas ao usuário
            if (!OperacaoValida()) return View(produtoViewModel);

            return RedirectToAction("Index");
        }

        [Route("produtos/consultar/{id:int}")]
        [HttpGet]
        public IActionResult Consultar(int id)
        {
            ProdutoViewModel _produtoViewModel = _mapper.Map<ProdutoViewModel>(_produtoService.ObterPorId(id));

            if (_produtoViewModel == null) return NotFound();

            return View(_produtoViewModel);
        }

        [Route("produtos/excluir/{id:int}")]
        [HttpGet]
        public IActionResult Excluir(int id)
        {
            ProdutoViewModel _produtoViewModel = _mapper.Map<ProdutoViewModel>(_produtoService.ObterPorId(id));

            if (_produtoViewModel == null) return NotFound();

            return View(_produtoViewModel);
        }

        [Route("produtos/excluir/{id:int}")]
        [HttpPost, ActionName("Excluir")]
        public IActionResult ExcluirProduto(int id)
        {
            ProdutoViewModel _produtoViewModel = _mapper.Map<ProdutoViewModel>(_produtoService.ObterPorId(id));

            if (_produtoViewModel == null) return NotFound();

            _produtoService.Excluir(id);

            // Verifica se há notificações vinda da camada de negócio
            // Caso tenha notificações, devem ser exibidas ao usuário
            if (!OperacaoValida()) return View(_produtoViewModel);

            TempData["Sucesso"] = "Produto excluido com sucesso !!!";

            return RedirectToAction("Index");
        }

        private bool UploadArquivo(IFormFile imagemUpload, string imgPrefixo)
        {
            if (imagemUpload.Length <= 0) return false;

            string _path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/produtos", imgPrefixo + imagemUpload.FileName);

            if (System.IO.File.Exists(_path))
            {
                ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome !!!");

                return false;
            }

            using (FileStream _stream = new FileStream(_path, FileMode.Create))
            {
                imagemUpload.CopyToAsync(_stream);
            }

            return true;
        }
    }
}

src/KITAB.SQLite.CRUD.Web/Views/Produtos/Alterar.cshtml
@model KITAB.SQLite.CRUD.Web.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "Alteração do Produto";
}

<!-- BEGIN Content Header -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@ViewData["Title"]</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a></li>
                    <li class="breadcrumb-item active">Alteração</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- END Content Header -->

<!-- BEGIN Content -->
<section class="content">
    <div class="container-fluid">
        <form class="form-horizontal" method="post" enctype="multipart/form-data" asp-controller="Produtos" asp-action="Alterar">
            <div class="card-body">
                <div class="form-group row">
                    <vc:Summary></vc:Summary>
                </div>
                <div class="form-group row">
                    <label asp-for="Nome" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Descricao" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <textarea cols="40" rows="5" asp-for="Descricao" class="form-control"></textarea>
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Imagem Atual</label>
                    <div class="col-sm-10">
                        <img src="~/img/produtos/@Model.Imagem" alt="@Model.Imagem" style="width: 200px; height: 200px" />
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ImagemUpload" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="ImagemUpload" asp-for="ImagemUpload">
                            <label data-browse="Procurar" style="width: 400px" class="custom-file-label" for="ImagemUpload"></label>
                            <label style="display: none" id="img_nome"></label>
                        </div>
                        <span asp-validation-for="ImagemUpload" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Qtde" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10 input-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-boxes"></i>
                                </span>
                            </div>
                            <input asp-for="Qtde" class="form-control">
                        </div>
                        <span asp-validation-for="Qtde" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PrecoCusto" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10 input-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-money-bill-wave"></i>
                                </span>
                            </div>
                            <input asp-for="PrecoCusto" class="form-control">
                        </div>
                        <span asp-validation-for="PrecoCusto" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PrecoVenda" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10 input-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-money-bill-wave"></i>
                                </span>
                            </div>
                            <input asp-for="PrecoVenda" class="form-control">
                        </div>
                        <span asp-validation-for="PrecoVenda" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Situacao" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <select name="Situacao" id="ddlSituacao">
                            <option selected="selected" value="A">Ativado</option>
                            <option value="D">Desativado</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-info float-right" asp-controller="Produtos" asp-action="Index">Voltar</a>
            </div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Imagem" />
        </form>
    </div>
</section>
<!-- END Content -->

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        // Posiciona o DROPDOWNLIST da situação de acordo com o que vier do BD
        document.getElementById('ddlSituacao').value = '@Model.Situacao';

        $("#ImagemUpload").change(function () {
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });
    </script>
}

src/KITAB.SQLite.CRUD.Web/Views/Produtos/Excluir.cshtml
@model KITAB.SQLite.CRUD.Web.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "Exclusão do Produto";
}

<!-- BEGIN Content Header -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@ViewData["Title"]</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a></li>
                    <li class="breadcrumb-item active">Exclusão</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- END Content Header -->
<!-- BEGIN Content -->
<section class="content">
    <div class="container-fluid">
        <div class="card-body">
            <div class="form-group row">
                <vc:Summary></vc:Summary>
            </div>
            <div class="form-group row">
                <label asp-for="Nome" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="Nome" class="form-control" disabled>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Descricao" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <textarea cols="40" rows="5" asp-for="Descricao" class="form-control" disabled></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Imagem Atual</label>
                <div class="col-sm-10">
                    <img src="~/img/produtos/@Model.Imagem" alt="@Model.Imagem" style="width: 200px; height: 200px" />
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Qtde" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10 input-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-boxes"></i>
                            </span>
                        </div>
                        <input asp-for="Qtde" class="form-control" disabled>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="PrecoCusto" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10 input-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-money-bill-wave"></i>
                            </span>
                        </div>
                        <input asp-for="PrecoCusto" class="form-control" disabled>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="PrecoVenda" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10 input-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-money-bill-wave"></i>
                            </span>
                        </div>
                        <input asp-for="PrecoVenda" class="form-control" disabled>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Situacao" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <select name="Situacao" id="ddlSituacao" disabled>
                        <option selected="selected" value="A">Ativado</option>
                        <option value="D">Desativado</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <form asp-controller="Produtos" asp-action="Excluir">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Excluir" class="btn btn-danger" />
                <a class="btn btn-info float-right" asp-controller="Produtos" asp-action="Index">Voltar</a>
            </form>
        </div>
    </div>
</section>
<!-- END Content -->

@section Scripts
{
    <script>
        // Posiciona o DROPDOWNLIST da situação de acordo com o que vier do BD
        document.getElementById('ddlSituacao').value = '@Model.Situacao';
    </script>
}

src/KITAB.SQLite.CRUD.Web/Views/Produtos/Index.cshtml
@model IEnumerable<KITAB.SQLite.CRUD.Web.ViewModels.ProdutoViewModel>

@{
    ViewData["Title"] = "Lista de Produtos";
}

<!-- BEGIN Content Header -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@ViewData["Title"]</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item active">Produtos</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- END Content Header -->

<!-- BEGIN Content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <vc:Summary></vc:Summary>
            </div>
            <div class="col-sm-12">
                <p><a class="btn btn-info" asp-controller="Produtos" asp-action="Inserir">Novo Produto</a></p>
            </div>
            <partial name="_ListaProdutos" />
        </div>
    </div>
</section>
<!-- END Content -->

src/KITAB.SQLite.CRUD.Web/Views/Produtos/Inserir.cshtml
@model KITAB.SQLite.CRUD.Web.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "Novo Produto";
}

<!-- BEGIN Content Header -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@ViewData["Title"]</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a></li>
                    <li class="breadcrumb-item active">Novo</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- END Content Header -->

<!-- BEGIN Content -->
<section class="content">
    <div class="container-fluid">
        <form class="form-horizontal" method="post" enctype="multipart/form-data" asp-controller="Produtos" asp-action="Inserir">
            <div class="card-body">
                <div class="form-group row">
                    <vc:Summary></vc:Summary>
                </div>
                <div class="form-group row">
                    <label asp-for="Nome" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input asp-for="Nome" class="form-control">
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Descricao" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <textarea cols="40" rows="5" asp-for="Descricao" class="form-control"></textarea>
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ImagemUpload" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="ImagemUpload" asp-for="ImagemUpload">
                            <label data-browse="Procurar" style="width: 400px" class="custom-file-label" for="ImagemUpload"></label>
                            <label style="display: none" id="img_nome"></label>
                        </div>
                        <span asp-validation-for="ImagemUpload" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Qtde" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10 input-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-boxes"></i>
                                </span>
                            </div>
                            <input asp-for="Qtde" class="form-control">
                        </div>
                        <span asp-validation-for="Qtde" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PrecoCusto" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10 input-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-money-bill-wave"></i>
                                </span>
                            </div>
                            <input asp-for="PrecoCusto" class="form-control">
                        </div>
                        <span asp-validation-for="PrecoCusto" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PrecoVenda" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10 input-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-money-bill-wave"></i>
                                </span>
                            </div>
                            <input asp-for="PrecoVenda" class="form-control">
                        </div>
                        <span asp-validation-for="PrecoVenda" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Situacao" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <select name="Situacao" id="ddlSituacao">
                            <option selected="selected" value="A">Ativado</option>
                            <option value="D">Desativado</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
                <a class="btn btn-info float-right" asp-controller="Produtos" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</section>
<!-- END Content -->

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $("#ImagemUpload").change(function () {
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });

        $("#ImagemUpload").attr("data-val", "true");
        $("#ImagemUpload").attr("data-val-required", "Preencha o campo Imagem...");
    </script>
}

src/KITAB.SQLite.CRUD.Web/Views/Produtos/_ListaProdutos.cshtml
@using KITAB.SQLite.CRUD.Web.Extensions
@model IEnumerable<KITAB.SQLite.CRUD.Web.ViewModels.ProdutoViewModel>

<div class="col-md-12" style="margin-top: 10px;">
    <form class="form-horizontal" method="get" asp-controller="Produtos" asp-action="Index">
        <div class="form-group row">
            <div class="col-sm-1" style="margin-bottom: 10px;">
                <label for="Produto" class="col-form-label">Produto:</label>
            </div>
            <div class="col-sm-3" style="margin-bottom: 10px;">
                <input type="text" name="filter" style="width: 250px;">
            </div>
            <div class="col-sm-2" style="margin-bottom: 10px;">
                <input class="btn btn-secondary" type="submit" value="PESQUISAR">
            </div>
            <div class="col-sm-2" style="margin-bottom: 10px;">
                <a class="btn btn-secondary" asp-controller="Produtos" asp-action="Index">LISTAR TODOS</a>
            </div>
        </div>
    </form>
</div>

<div class="col-md-12 table-responsive p-0">
    <table class="table table-hover table-striped text-nowrap">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.ActionLink("Id", "Index", "Produtos", new { sortField = "Id", currentSortField = ViewBag.Paginacao.SortField, currentSortOrder = ViewBag.Paginacao.SortOrder, currentFilter = ViewBag.Paginacao.Filter })
                </th>
                <th>
                    @Html.ActionLink("Produto", "Index", "Produtos", new { sortField = "Nome", currentSortField = ViewBag.Paginacao.SortField, currentSortOrder = ViewBag.Paginacao.SortOrder, currentFilter = ViewBag.Paginacao.Filter })
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Qtde)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PrecoCusto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PrecoVenda)
                </th>
                <th>
                    @Html.ActionLink("Situação", "Index", "Produtos", new { sortField = "Situacao", currentSortField = ViewBag.Paginacao.SortField, currentSortOrder = ViewBag.Paginacao.SortOrder, currentFilter = ViewBag.Paginacao.Filter })
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @item.Qtde
                    </td>
                    <td>
                        @item.PrecoCusto.ToString("C")
                    </td>
                    <td>
                        @item.PrecoVenda.ToString("C")
                    </td>
                    <td>
                        @this.FormataSituacao(item.Situacao)
                    </td>
                    <td class="text-right">
                        <a class="btn btn-warning" asp-controller="Produtos" asp-action="Consultar" asp-route-id="@item.Id"><span class="fa fa-search"></span></a>
                        <a class="btn btn-info" asp-controller="Produtos" asp-action="Alterar" asp-route-id="@item.Id"><span class="fa fa-pencil-alt"></span></a>
                        <a class="btn btn-danger" asp-controller="Produtos" asp-action="Excluir" asp-route-id="@item.Id"><span class="fa fa-trash"></span></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="col-md-12" style="margin-top: 20px;">
    @await Component.InvokeAsync("Pagination")
</div>